version: '3.9'

services:
  database:
    image: postgres:16-alpine
    env_file: .env.development
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - fullstack
    ports:
      - '5432:5432'
    environment:
        POSTGRES_DB: 'movies'
        POSTGRES_PASSWORD: 'postgres'

networks:
  fullstack:

volumes:
  postgres-data:
