version: '3.9'

services:
  web:
    image: nestjs-dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      # ✨ Target the dev stage
      target: dev
    volumes:
      - .:/app
      # This ensures that the NestJS container manages the node_modules folder
      # rather than synchronizes it with the host machine
      - node_modules:/app/node_modules
    ports:
        - '3000:3000'
    depends_on:
      - database
    command: 'npx nest start'
    networks:
      - fullstack
  database:
    image: postgres:16-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - fullstack
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres' 
      POSTGRES_DB: 'movies'

networks:
  fullstack:

volumes:
  postgres-data:
  node_modules:
